version: "3"
services:
  server:
    build: ./
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"