version: "3"
services:
  server:
    build: ./
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb
    volumes:
      - ./Logs:/app/Logs
  mongodb:
    image: mongo:4.4.6
    ports:
      - "27017:27017"